- name: Update, install and configure required packages
  hosts: cxt_03
  become: true
  tasks:
  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest
      update_cache: yes
  - name: Install glances
    apt:
      name: glances
      state: present
  - name: Install sysstat
    apt:
      name: sysstat
      state: present
  - name: Enable, start and ensure it is not masked service sysstat
    ansible.builtin.systemd:
      name: sysstat
      enabled: yes
      state: started
      masked: no
  - name: Create a glances config directory
    ansible.builtin.file:
      path: /home/ubuntu/.config/glances/
      state: directory
      mode: '0755'
  - name: Creating a glances.conf file
    copy:
      dest: /home/ubuntu/.config/glances/glances.conf
      content: |
        [opentsdb]
        host=54.77.161.219
        port=4242
        prefix=glances
        tags=user:TeixeiraCrespo,host:cxt03
  - name: Install python3-pip
    apt:
      name: python3-pip
      state: present
  - name: Install potsdb
    pip:
      name: potsdb
  - name: Check if reboot is needed
    stat:
      path: /var/run/reboot-required
    register: stat_result
  - name: Reboot if needed
    reboot:
    when: stat_result.stat.exists
