---
- name: Add public keys
  hosts: cxt
  become: yes
  remote_user: ubuntu

  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/home/teixe/.ssh/id_rsa.pub') }}"
